//
//  RecordEditorView.swift
//  PocketBaseAdminApp
//
//  Created by Claude Code on behalf of Brianna Zamora
//

import SwiftUI
import PocketBase
import PocketBaseAdmin
import UniformTypeIdentifiers
import PhotosUI

struct RecordEditorView: View {
    let collection: CollectionModel
    let record: RecordModel?
    let onSave: () async -> Void

    @Environment(\.pocketbase) private var pocketbase
    @Environment(\.dismiss) private var dismiss

    @State private var fieldValues: [String: JSONValue] = [:]
    @State private var pendingFiles: [String: [UploadFile]] = [:]
    @State private var isSaving = false
    @State private var errorMessage: String?

    private var isEditing: Bool { record != nil }

    private var schema: [Field] {
        collection.schema ?? []
    }

    /// Fields that should not be editable in the record editor
    private static let systemFieldNames: Set<String> = [
        "id", "created", "updated", "collectionId", "collectionName", "expand"
    ]

    private var editableFields: [Field] {
        schema.filter { field in
            // Skip system fields
            guard !field.system else { return false }
            // Skip known system field names
            guard !Self.systemFieldNames.contains(field.name) else { return false }
            // Skip autodate fields (auto-managed by PocketBase)
            guard field.type != .autodate else { return false }
            // Skip primaryKey fields (auto-generated by PocketBase, like id)
            guard field.type != .primaryKey else { return false }
            return true
        }
    }

    var body: some View {
        NavigationStack {
            Form {
                if let errorMessage {
                    Section {
                        Label(errorMessage, systemImage: "exclamationmark.triangle")
                            .foregroundStyle(.red)
                    }
                }

                if editableFields.isEmpty {
                    ContentUnavailableView {
                        Label("No Fields", systemImage: "rectangle.dashed")
                    } description: {
                        Text("This collection has no editable fields. Add fields to the collection schema first.")
                    }
                }

                ForEach(editableFields, id: \.id) { field in
                    Section {
                        FieldEditorRow(
                            field: field,
                            value: binding(for: field.name),
                            pocketbase: pocketbase,
                            onFileSelected: { fieldName, file in
                                addPendingFile(fieldName: fieldName, file: file)
                            }
                        )
                    } header: {
                        HStack {
                            Text(field.name)
                            if field.required == true {
                                Text("*")
                                    .foregroundStyle(.red)
                            }
                        }
                    } footer: {
                        if let options = field.options {
                            fieldOptionsFooter(field: field, options: options)
                        }
                    }
                }
            }
            .navigationTitle(isEditing ? "Edit Record" : "New Record")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                    .disabled(isSaving)
                }

                ToolbarItem(placement: .confirmationAction) {
                    Button(isEditing ? "Save" : "Create") {
                        Task {
                            await saveRecord()
                        }
                    }
                    .disabled(isSaving)
                }
            }
            .interactiveDismissDisabled(isSaving)
        }
        .onAppear {
            initializeFieldValues()
        }
    }

    private func binding(for fieldName: String) -> Binding<JSONValue> {
        Binding(
            get: { fieldValues[fieldName] ?? .null },
            set: { fieldValues[fieldName] = $0 }
        )
    }

    @ViewBuilder
    private func fieldOptionsFooter(field: Field, options: FieldOptions) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            if let min = options.min {
                Text("Min: \(min)")
            }
            if let max = options.max {
                Text("Max: \(max)")
            }
            if let maxSize = options.maxSize {
                Text("Max size: \(ByteCountFormatter.string(fromByteCount: Int64(maxSize), countStyle: .file))")
            }
            if let values = options.values, !values.isEmpty {
                Text("Options: \(values.joined(separator: ", "))")
            }
        }
        .font(.caption)
        .foregroundStyle(.secondary)
    }

    private func initializeFieldValues() {
        if let record {
            // Edit mode: populate with existing values
            fieldValues = record.content
        } else {
            // Create mode: initialize with defaults
            for field in editableFields {
                fieldValues[field.name] = defaultValue(for: field)
            }
        }
    }

    private func defaultValue(for field: Field) -> JSONValue {
        switch field.type {
        case .bool:
            return .bool(false)
        case .number:
            return .int(0)
        case .text, .editor, .email, .url, .password:
            return .string("")
        case .select:
            if let values = field.options?.values, !values.isEmpty {
                return .string(values[0])
            }
            return .string("")
        case .json, .geoPoint:
            return .dictionary([:])
        case .date, .dateTime, .autodate:
            return .date(Date())
        case .file, .relation:
            return .null
        case .customEmail:
            return .string("")
        case .primaryKey:
            return .string("")
        case .unknown:
            return .string("")
        }
    }

    private func saveRecord() async {
        isSaving = true
        errorMessage = nil
        defer { isSaving = false }

        // Filter out system fields and only include editable field values
        let editableFieldNames = Set(editableFields.map(\.name))
        var dataToSend = fieldValues.filter { key, _ in
            editableFieldNames.contains(key)
        }

        // Explicitly remove any system fields that might have crept in
        for systemField in Self.systemFieldNames {
            dataToSend.removeValue(forKey: systemField)
        }

        // Remove file field values from data when we have actual file uploads
        // (the file upload replaces the string value)
        for fieldName in pendingFiles.keys {
            dataToSend.removeValue(forKey: fieldName)
        }

        // Debug: print what we're sending
        print("DEBUG: Creating record with fields: \(dataToSend.keys.sorted())")
        print("DEBUG: Schema fields: \(schema.map { "\($0.name) (type: \($0.type.rawValue), system: \($0.system))" })")
        print("DEBUG: Editable fields: \(editableFields.map(\.name))")
        print("DEBUG: Pending files: \(pendingFiles.keys.sorted())")

        do {
            if let record {
                // Update existing record
                if pendingFiles.isEmpty {
                    _ = try await pocketbase.admin
                        .records(collection.name)
                        .update(id: record.id, dataToSend)
                } else {
                    _ = try await pocketbase.admin
                        .records(collection.name)
                        .update(id: record.id, dataToSend, files: pendingFiles)
                }
            } else {
                // Create new record
                if pendingFiles.isEmpty {
                    _ = try await pocketbase.admin
                        .records(collection.name)
                        .create(dataToSend)
                } else {
                    _ = try await pocketbase.admin
                        .records(collection.name)
                        .create(dataToSend, files: pendingFiles)
                }
            }

            await onSave()
            dismiss()
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    /// Adds a pending file upload for a field
    func addPendingFile(fieldName: String, file: UploadFile) {
        if pendingFiles[fieldName] == nil {
            pendingFiles[fieldName] = []
        }
        pendingFiles[fieldName]?.append(file)
    }
}

struct FieldEditorRow: View {
    let field: Field
    @Binding var value: JSONValue
    var pocketbase: PocketBase?
    var onFileSelected: ((String, UploadFile) -> Void)?

    @State private var showFilePicker = false
    @State private var selectedFileURL: URL?
    @State private var selectedFileName: String?

    @State private var showRelationPicker = false

    var body: some View {
        switch field.type {
        case .text:
            TextField("", text: stringBinding, prompt: Text("Enter \(field.name)"))
        case .editor:
            TextEditor(text: stringBinding)
                .frame(minHeight: 100)
        case .number:
            TextField("", value: numberBinding, format: .number, prompt: Text("0"))
            #if os(iOS)
                .keyboardType(.decimalPad)
            #endif
        case .bool:
            Toggle("Enabled", isOn: boolBinding)
        case .email:
            TextField("", text: stringBinding, prompt: Text("email@example.com"))
            #if os(iOS)
                .keyboardType(.emailAddress)
                .textContentType(.emailAddress)
                .autocapitalization(.none)
            #endif
        case .url:
            TextField("", text: stringBinding, prompt: Text("https://"))
            #if os(iOS)
                .keyboardType(.URL)
                .textContentType(.URL)
                .autocapitalization(.none)
            #endif
        case .password:
            SecureField("", text: stringBinding, prompt: Text("Password"))
        case .date:
            DatePicker(
                "",
                selection: dateBinding,
                displayedComponents: .date
            )
            .labelsHidden()
        case .dateTime, .autodate:
            DatePicker(
                "",
                selection: dateBinding,
                displayedComponents: [.date, .hourAndMinute]
            )
            .labelsHidden()
        case .select:
            if let options = field.options?.values, !options.isEmpty {
                Picker("", selection: stringBinding) {
                    ForEach(options, id: \.self) { option in
                        Text(option).tag(option)
                    }
                }
                .labelsHidden()
            } else {
                TextField("", text: stringBinding, prompt: Text("Enter value"))
            }
        case .json:
            TextEditor(text: jsonStringBinding)
                .frame(minHeight: 100)
                .font(.system(.body, design: .monospaced))
        case .file:
            FileFieldEditor(
                field: field,
                value: $value,
                showFilePicker: $showFilePicker,
                selectedFileName: $selectedFileName,
                onFileSelected: onFileSelected
            )
            .fileImporter(
                isPresented: $showFilePicker,
                allowedContentTypes: allowedFileTypes,
                allowsMultipleSelection: field.options?.maxSelect ?? 1 > 1
            ) { result in
                handleFileSelection(result)
            }
        case .relation:
            RelationFieldEditor(
                field: field,
                value: $value,
                showRelationPicker: $showRelationPicker,
                pocketbase: pocketbase
            )
            .sheet(isPresented: $showRelationPicker) {
                if let collectionId = field.options?.collectionId, let pocketbase {
                    RelationPickerSheet(
                        collectionId: collectionId,
                        maxSelect: field.options?.maxSelect ?? 1,
                        selectedIds: relationIdsBinding,
                        pocketbase: pocketbase
                    )
                }
            }
        case .customEmail:
            TextField("", text: stringBinding, prompt: Text("email@example.com"))
            #if os(iOS)
                .keyboardType(.emailAddress)
            #endif
        case .primaryKey:
            TextField("", text: stringBinding, prompt: Text("ID"))
                .font(.system(.body, design: .monospaced))
                .disabled(true)
        case .geoPoint:
            TextEditor(text: jsonStringBinding)
                .frame(minHeight: 60)
                .font(.system(.body, design: .monospaced))
        case .unknown:
            TextField("", text: stringBinding, prompt: Text("Enter value"))
        }
    }

    private var allowedFileTypes: [UTType] {
        guard let mimeTypes = field.options?.mimeTypes, !mimeTypes.isEmpty else {
            return [.data]
        }
        return mimeTypes.compactMap { mimeType in
            UTType(mimeType: mimeType)
        }
    }

    private func handleFileSelection(_ result: Result<[URL], Error>) {
        switch result {
        case .success(let urls):
            for url in urls {
                // Start accessing the security-scoped resource
                guard url.startAccessingSecurityScopedResource() else {
                    continue
                }
                defer { url.stopAccessingSecurityScopedResource() }

                do {
                    let uploadFile = try UploadFile(url: url)
                    selectedFileName = url.lastPathComponent
                    value = .string(url.lastPathComponent)
                    onFileSelected?(field.name, uploadFile)
                } catch {
                    print("Failed to read file: \(error)")
                }
            }
        case .failure(let error):
            print("File selection failed: \(error)")
        }
    }

    private var relationIdsBinding: Binding<[String]> {
        Binding(
            get: {
                switch value {
                case .string(let s) where !s.isEmpty:
                    return [s]
                case .array(let arr):
                    return arr.compactMap { item in
                        if case .string(let s) = item { return s }
                        return nil
                    }
                default:
                    return []
                }
            },
            set: { newIds in
                if field.options?.maxSelect == 1 {
                    value = newIds.first.map { .string($0) } ?? .null
                } else {
                    value = .array(newIds.map { .string($0) })
                }
            }
        )
    }

    // MARK: - Bindings

    private var stringBinding: Binding<String> {
        Binding(
            get: {
                switch value {
                case .string(let s): return s
                case .url(let url): return url.absoluteString
                case .int(let i): return String(i)
                case .double(let d): return String(d)
                default: return ""
                }
            },
            set: { value = .string($0) }
        )
    }

    private var boolBinding: Binding<Bool> {
        Binding(
            get: {
                if case .bool(let b) = value { return b }
                return false
            },
            set: { value = .bool($0) }
        )
    }

    private var numberBinding: Binding<Double> {
        Binding(
            get: {
                switch value {
                case .int(let i): return Double(i)
                case .double(let d): return d
                case .decimal(let d): return NSDecimalNumber(decimal: d).doubleValue
                default: return 0
                }
            },
            set: {
                if $0.truncatingRemainder(dividingBy: 1) == 0 {
                    value = .int(Int($0))
                } else {
                    value = .double($0)
                }
            }
        )
    }

    private var dateBinding: Binding<Date> {
        Binding(
            get: {
                if case .date(let d) = value { return d }
                return Date()
            },
            set: { value = .date($0) }
        )
    }

    private var jsonStringBinding: Binding<String> {
        Binding(
            get: {
                // Serialize JSONValue to string for editing
                do {
                    let data = try JSONEncoder().encode(value)
                    return String(data: data, encoding: .utf8) ?? "{}"
                } catch {
                    return "{}"
                }
            },
            set: { newString in
                // Try to parse as JSON
                if let data = newString.data(using: .utf8),
                   let parsed = try? JSONDecoder().decode(JSONValue.self, from: data) {
                    value = parsed
                }
            }
        )
    }
}

// MARK: - File Field Editor

struct FileFieldEditor: View {
    let field: Field
    @Binding var value: JSONValue
    @Binding var showFilePicker: Bool
    @Binding var selectedFileName: String?
    var onFileSelected: ((String, UploadFile) -> Void)?

    @State private var showPhotosPicker = false
    @State private var showCamera = false
    @State private var selectedPhotoItem: PhotosPickerItem?

    private var currentFileName: String? {
        switch value {
        case .string(let s) where !s.isEmpty:
            return s
        case .array(let arr):
            return arr.compactMap { item -> String? in
                if case .string(let s) = item { return s }
                return nil
            }.first
        default:
            return nil
        }
    }

    /// Check if the field accepts images
    private var acceptsImages: Bool {
        guard let mimeTypes = field.options?.mimeTypes, !mimeTypes.isEmpty else {
            return true // No restrictions, accept images
        }
        return mimeTypes.contains { $0.hasPrefix("image/") || $0 == "image/*" }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            if let fileName = selectedFileName ?? currentFileName {
                HStack {
                    Image(systemName: "doc.fill")
                        .foregroundStyle(.blue)
                    Text(fileName)
                        .lineLimit(1)
                    Spacer()
                    Button(role: .destructive) {
                        value = .null
                        selectedFileName = nil
                    } label: {
                        Image(systemName: "xmark.circle.fill")
                            .foregroundStyle(.secondary)
                    }
                    .buttonStyle(.plain)
                }
                .padding(8)
                .background(
                    RoundedRectangle(cornerRadius: 8)
                        .fill(Color.secondary.opacity(0.1))
                )
            }

            Menu {
                #if os(iOS)
                if acceptsImages {
                    Button {
                        showCamera = true
                    } label: {
                        Label("Take Photo", systemImage: "camera")
                    }

                    Button {
                        showPhotosPicker = true
                    } label: {
                        Label("Photo Library", systemImage: "photo.on.rectangle")
                    }
                }
                #endif

                Button {
                    showFilePicker = true
                } label: {
                    Label("Browse Files", systemImage: "folder")
                }
            } label: {
                Label("Choose File", systemImage: "plus.circle")
            }
            .buttonStyle(.bordered)
            .photosPicker(isPresented: $showPhotosPicker, selection: $selectedPhotoItem, matching: .images)
            .onChange(of: selectedPhotoItem) { _, newItem in
                guard let newItem else { return }
                Task {
                    if let data = try? await newItem.loadTransferable(type: Data.self) {
                        let fileName = "photo_\(Date().timeIntervalSince1970).jpg"
                        selectedFileName = fileName
                        value = .string(fileName)
                        let uploadFile = UploadFile(filename: fileName, data: data, mimeType: "image/jpeg")
                        onFileSelected?(field.name, uploadFile)
                    }
                }
            }
            #if os(iOS)
            .fullScreenCover(isPresented: $showCamera) {
                CameraView { image in
                    if let data = image.jpegData(compressionQuality: 0.8) {
                        let fileName = "photo_\(Date().timeIntervalSince1970).jpg"
                        selectedFileName = fileName
                        value = .string(fileName)
                        let uploadFile = UploadFile(filename: fileName, data: data, mimeType: "image/jpeg")
                        onFileSelected?(field.name, uploadFile)
                    }
                }
            }
            #endif

            if let maxSize = field.options?.maxSize {
                Text("Max size: \(ByteCountFormatter.string(fromByteCount: Int64(maxSize), countStyle: .file))")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            if let mimeTypes = field.options?.mimeTypes, !mimeTypes.isEmpty {
                Text("Allowed: \(mimeTypes.joined(separator: ", "))")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
    }
}

// MARK: - Camera View

#if os(iOS)
import UIKit

struct CameraView: UIViewControllerRepresentable {
    var onCapture: (UIImage) -> Void
    @Environment(\.dismiss) private var dismiss

    func makeUIViewController(context: Context) -> UIImagePickerController {
        let picker = UIImagePickerController()
        picker.sourceType = .camera
        picker.delegate = context.coordinator
        return picker
    }

    func updateUIViewController(_ uiViewController: UIImagePickerController, context: Context) {}

    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }

    class Coordinator: NSObject, UIImagePickerControllerDelegate, UINavigationControllerDelegate {
        let parent: CameraView

        init(_ parent: CameraView) {
            self.parent = parent
        }

        func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey: Any]) {
            if let image = info[.originalImage] as? UIImage {
                parent.onCapture(image)
            }
            parent.dismiss()
        }

        func imagePickerControllerDidCancel(_ picker: UIImagePickerController) {
            parent.dismiss()
        }
    }
}
#endif

// MARK: - Relation Field Editor

struct RelationFieldEditor: View {
    let field: Field
    @Binding var value: JSONValue
    @Binding var showRelationPicker: Bool
    var pocketbase: PocketBase?

    private var selectedIds: [String] {
        switch value {
        case .string(let s) where !s.isEmpty:
            return [s]
        case .array(let arr):
            return arr.compactMap { item in
                if case .string(let s) = item { return s }
                return nil
            }
        default:
            return []
        }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            if !selectedIds.isEmpty {
                ForEach(selectedIds, id: \.self) { id in
                    HStack {
                        Image(systemName: "link")
                            .foregroundStyle(.blue)
                        Text(id)
                            .font(.system(.body, design: .monospaced))
                            .lineLimit(1)
                        Spacer()
                        Button(role: .destructive) {
                            removeRelation(id)
                        } label: {
                            Image(systemName: "xmark.circle.fill")
                                .foregroundStyle(.secondary)
                        }
                        .buttonStyle(.plain)
                    }
                    .padding(8)
                    .background(
                        RoundedRectangle(cornerRadius: 8)
                            .fill(Color.secondary.opacity(0.1))
                    )
                }
            }

            if pocketbase != nil && field.options?.collectionId != nil {
                Button {
                    showRelationPicker = true
                } label: {
                    Label("Select Record", systemImage: "magnifyingglass")
                }
                .buttonStyle(.bordered)
            } else {
                TextField("Record ID", text: manualIdBinding)
                    .font(.system(.body, design: .monospaced))
            }

            if let collectionId = field.options?.collectionId {
                Text("Related to: \(collectionId)")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
    }

    private var manualIdBinding: Binding<String> {
        Binding(
            get: { selectedIds.first ?? "" },
            set: { newValue in
                if newValue.isEmpty {
                    value = .null
                } else {
                    value = .string(newValue)
                }
            }
        )
    }

    private func removeRelation(_ id: String) {
        var ids = selectedIds
        ids.removeAll { $0 == id }

        if ids.isEmpty {
            value = .null
        } else if field.options?.maxSelect == 1 {
            value = ids.first.map { .string($0) } ?? .null
        } else {
            value = .array(ids.map { .string($0) })
        }
    }
}

// MARK: - Relation Picker Sheet

struct RelationPickerSheet: View {
    let collectionId: String
    let maxSelect: Int
    @Binding var selectedIds: [String]
    let pocketbase: PocketBase

    @State private var records: [RecordModel] = []
    @State private var isLoading = false
    @State private var searchText = ""
    @State private var errorMessage: String?

    @Environment(\.dismiss) private var dismiss

    private var filteredRecords: [RecordModel] {
        if searchText.isEmpty {
            return records
        }
        return records.filter { record in
            record.id.localizedCaseInsensitiveContains(searchText) ||
            record.content.values.contains { value in
                if case .string(let s) = value {
                    return s.localizedCaseInsensitiveContains(searchText)
                }
                return false
            }
        }
    }

    var body: some View {
        NavigationStack {
            Group {
                if isLoading {
                    ProgressView()
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                } else if let errorMessage {
                    ContentUnavailableView {
                        Label("Error", systemImage: "exclamationmark.triangle")
                    } description: {
                        Text(errorMessage)
                    } actions: {
                        Button("Retry") {
                            Task {
                                await loadRecords()
                            }
                        }
                    }
                } else if records.isEmpty {
                    ContentUnavailableView {
                        Label("No Records", systemImage: "tray")
                    } description: {
                        Text("This collection has no records.")
                    }
                } else {
                    List(filteredRecords) { record in
                        RecordSelectionRow(
                            record: record,
                            isSelected: selectedIds.contains(record.id),
                            onToggle: {
                                toggleSelection(record.id)
                            }
                        )
                    }
                    .searchable(text: $searchText, prompt: "Search records")
                }
            }
            .navigationTitle("Select Record")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }

                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") {
                        dismiss()
                    }
                }
            }
        }
        .task {
            await loadRecords()
        }
    }

    private func loadRecords() async {
        isLoading = true
        errorMessage = nil
        defer { isLoading = false }

        do {
            let response = try await pocketbase.admin.records(collectionId).list(perPage: 100)
            records = response.items
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    private func toggleSelection(_ id: String) {
        if selectedIds.contains(id) {
            selectedIds.removeAll { $0 == id }
        } else {
            if maxSelect == 1 {
                selectedIds = [id]
            } else if selectedIds.count < maxSelect {
                selectedIds.append(id)
            }
        }
    }
}

struct RecordSelectionRow: View {
    let record: RecordModel
    let isSelected: Bool
    let onToggle: () -> Void

    var body: some View {
        Button(action: onToggle) {
            HStack {
                Image(systemName: isSelected ? "checkmark.circle.fill" : "circle")
                    .foregroundStyle(isSelected ? .blue : .secondary)

                VStack(alignment: .leading, spacing: 2) {
                    Text(record.id)
                        .font(.system(.body, design: .monospaced))

                    if let displayValue = primaryDisplayValue {
                        Text(displayValue)
                            .font(.caption)
                            .foregroundStyle(.secondary)
                            .lineLimit(1)
                    }
                }

                Spacer()
            }
        }
        .buttonStyle(.plain)
    }

    private var primaryDisplayValue: String? {
        // Try common field names for display
        for key in ["name", "title", "email", "username", "label"] {
            if case .string(let s) = record.content[key], !s.isEmpty {
                return s
            }
        }
        return nil
    }
}
